apiVersion: v1 
kind: Pod 
metadata:
  name: environment 
  labels: 
    project: expense 
    module: backend
    environment: dev
  annotations:
    imageRegistry: "https://www.docker.com/"
    buildURL: "https://jenkins.docker.com/expense/dev/84"
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env: 
    - name: course
      value: devops
    - name: duration
      value: "120 hrs"
    - name: trainer
      value: Amarnath