apiVersion: v1 
kind: Pod 
metadata: 
  name: resource-limits
  labels: 
    project: expense 
    environment: dev 
    module: backend 
  annotations: 
    imageRegistry: "https://www.docker.com/"
    buildURL: "https://jenkins.docker.com/expense/dev/84"
spec: 
  containers: 
  - name: nginx 
    image: nginx
    ports: 
    - containerPort: 80 
    env: 
    - name: course
      value: AWS devops 
    - name: duration
      value: 120 hrs
    - name: trainer
      value: Amarnath
    resources:
      requests: 
        memory: 68mi
        cpu: 100m
      limits:
        memory: 68mi
        cpu: 100m

