apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  labels:
    project: expense
    environment: dev
    module: backend
  annotations:
    imageRegistry: "https://www.docker.com/"
    buildURL: "https://jenkins.docker.com/expense/dev/84"
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
      - configMapRef:
          name: nginx-config
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nginx-config # name of the configmap you are referring to
    #       key: course
    # - name: duration
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nginx-config
    #       key: duration


