apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    project: expense
    environment: dev
    module: backend
  annotations:
    imageRegistry: "https://www.docker.com/"
    buildURL: "https://jenkins.docker.com/expense/dev/84"
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-sample